# Makefile for PyEI package

# Docker settings
DOCKER_IMAGE_NAME = pyei
DOCKER_CONTAINER_NAME = pyei-dev

# Phony targets
.PHONY: build test lint bash clean install pre-commit help update-requirements freeze-requirements ci-lint ci-test

# Default target
help:
	@echo "Available targets:"
	@echo "  build      - Build the Docker image"
	@echo "  test       - Run tests in Docker container"
	@echo "  lint       - Run linting checks in Docker container"
	@echo "  bash       - Start interactive bash session in Docker container"
	@echo "  install    - Install package in development mode locally"
	@echo "  pre-commit - Run pre-commit hooks in Docker container"
	@echo "  clean      - Remove Docker containers and images"
	@echo "  help       - Show this help message"
	@echo "  update-requirements - Update requirements.lock with current versions"
	@echo "  freeze-requirements - Show current package versions"
	@echo "  ci-lint    - Run linting for CI (without Docker)"
	@echo "  ci-test    - Run tests for CI (without Docker)"

# Build Docker image
build:
	docker build -t $(DOCKER_IMAGE_NAME) .

# Run tests in Docker
test: build
	docker run --rm \
		-v $(PWD):/app \
		$(DOCKER_IMAGE_NAME) \
		pytest -vx --cov pyei

# Run linting in Docker
lint: build
	docker run --rm \
		-v $(PWD):/app \
		$(DOCKER_IMAGE_NAME) \
		sh -c "ruff check . && ruff format --check . && mypy --ignore-missing-imports pyei"

# Start interactive bash session in Docker
bash: build
	docker run --rm -it \
		-v $(PWD):/app \
		--name $(DOCKER_CONTAINER_NAME) \
		$(DOCKER_IMAGE_NAME) \
		/bin/bash

# Install package locally (for development without Docker)
install:
	pip install -e .
	pip install -r requirements-dev.txt

# Run pre-commit hooks in Docker
pre-commit: build
	docker run --rm \
		-v $(PWD):/app \
		$(DOCKER_IMAGE_NAME) \
		sh -c "pre-commit install && pre-commit run --all-files"

# Clean up Docker resources
clean:
	-docker stop $(DOCKER_CONTAINER_NAME) 2>/dev/null || true
	-docker rm $(DOCKER_CONTAINER_NAME) 2>/dev/null || true
	-docker rmi $(DOCKER_IMAGE_NAME) 2>/dev/null || true

# Requirements management
update-requirements: build
	@echo "Updating requirements.lock with current package versions..."
	docker run --rm -v $(PWD):/app $(DOCKER_IMAGE_NAME) \
		sh -c "/root/.local/bin/uv pip freeze > requirements.lock && \
		echo '# This file contains the exact versions of all dependencies (including transitive ones)' > temp && \
		echo '# Generated by: make update-requirements' >> temp && \
		echo '# Date: $(shell date +%Y-%m-%d)' >> temp && \
		echo '# Python version: 3.10' >> temp && \
		echo '' >> temp && \
		cat requirements.lock >> temp && \
		mv temp requirements.lock"
	@echo "Requirements lock file updated!"

freeze-requirements: build
	@echo "Current package versions:"
	docker run --rm -v $(PWD):/app $(DOCKER_IMAGE_NAME) \
		/root/.local/bin/uv pip freeze

# CI targets (without Docker for GitHub Actions)
ci-lint:
	ruff check .
	ruff format
	mypy --ignore-missing-imports pyei

ci-test:
	pytest -vx --cov pyei

# Legacy targets for compatibility
lint-and-test: lint test
	@echo "Linting and testing completed successfully!"
